const { test } = require('node:test');
const assert = require('node:assert/strict');
const { chromium } = require('playwright');
const { existsSync } = require('node:fs');
process.env.JWT_SECRET = 'browser-test-secret-at-least-32-bytes';

test('PWA: edición offline, persistencia, navegación y sincronización sin contraseñas guardadas', async t => {
    const app = require('./server');
    const pool = require('./config/database');
    const server = app.listen(0, '127.0.0.1');
    await new Promise(resolve => server.once('listening', resolve));
    let browser;
    t.after(async () => { await browser?.close(); await new Promise(resolve => server.close(resolve)); await pool.end(); });
    const edge = ['C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', 'C:/Program Files/Microsoft/Edge/Application/msedge.exe'].find(existsSync);
    browser = await chromium.launch(edge ? { executablePath: edge, headless: true } : { headless: true });
    const context = await browser.newContext();
    const base = `http://127.0.0.1:${server.address().port}`;
    let disconnected = false;
    const snapshot = { totalClientes: 1, totalMascotas: 1, totalUsuarios: 1, clientes: [{ id: 10, usuario_id: 1, nombre: 'Ana', apellido: 'Pérez', email: 'ana@example.test', telefono: '5551234567', direccion: '' }], mascotas: [{ id: 20, cliente_id: 10, nombre: 'Luna', especie: 'perro', raza: '', sexo: 'hembra', fecha_nacimiento: '2022-03-04', color: '', observaciones: '', propietario: 'Ana Pérez', telefono: '5551234567' }] };
    const receipts = new Map();
    await context.route('**/api/**', async route => {
        if (disconnected) return route.abort('internetdisconnected');
        const path = new URL(route.request().url()).pathname;
        let data;
        if (path === '/api/auth/sesion') data = { usuario: { id: 1, email: 'ana@example.test', rol: 'cliente' } };
        else if (path === '/api/dashboard') data = snapshot;
        else if (path === '/api/sync') {
            const { operation } = route.request().postDataJSON();
            if (receipts.has(operation.id)) data = receipts.get(operation.id);
            else {
                if (operation.type === 'pet:create') snapshot.mascotas.unshift({ ...operation.values, id: 21, propietario: 'Ana Pérez' });
                if (operation.type === 'pet:update') Object.assign(snapshot.mascotas.find(row => String(row.id) === String(operation.target)), operation.values);
                if (operation.type === 'user:update') Object.assign(snapshot.clientes[0], operation.values);
                snapshot.totalMascotas = snapshot.mascotas.length;
                data = { id: operation.type.startsWith('pet:') ? 21 : 2, cliente_id: operation.type.startsWith('user:') ? 11 : undefined };
                receipts.set(operation.id, data);
            }
        } else return route.fulfill({ status: 404, json: { mensaje: 'Ruta no disponible' } });
        return route.fulfill({ json: data });
    });
    await context.addInitScript(() => { sessionStorage.setItem('veterinaria.token', 'x.' + btoa(JSON.stringify({ id: 1 })) + '.x'); });
    const page = await context.newPage();
    const errors = []; page.on('pageerror', error => errors.push(error.message));
    await page.goto(base + '/dashboard/dashboard.html');
    await page.waitForFunction(() => document.getElementById('tablaMascotas').textContent.includes('Luna'));
    await page.evaluate(() => navigator.serviceWorker.ready);
    await page.waitForFunction(() => Boolean(navigator.serviceWorker.controller));
    await page.getByRole('link', { name: 'Mascotas', exact: true }).click();
    assert.equal(await page.evaluate(() => location.hash), '#mascotas');
    await page.locator('#tablaMascotas button').click();
    await page.locator('#pet-form input[name="nombre"]').fill('Luna editada');
    await page.locator('#pet-form button[type="submit"]').click();
    await page.waitForFunction(() => document.getElementById('tablaMascotas').textContent.includes('Luna editada'));
    disconnected = true; await context.setOffline(true);
    await page.reload();
    await page.waitForFunction(() => document.getElementById('tablaMascotas').textContent.includes('Luna editada'));
    await page.locator('#register-pet').click();
    await page.locator('#pet-form input[name="nombre"]').fill('Sol offline');
    await page.locator('#pet-form button[type="submit"]').click();
    await page.waitForFunction(() => document.getElementById('tablaMascotas').textContent.includes('Sol offline'));
    await page.locator('#tablaClientes button').click();
    await page.locator('#user-form input[name="telefono"]').fill('5559876543');
    await page.locator('#user-form button[type="submit"]').click();
    await page.waitForFunction(() => document.getElementById('tablaClientes').textContent.includes('5559876543'));
    await page.locator('#register-user').click();
    for (const [name, value] of Object.entries({ nombre: 'Nueva', apellido: 'Cuenta', email: 'new@example.test', password: 'NeverPersist123!' })) await page.locator(`#user-form input[name="${name}"]`).fill(value);
    await page.locator('#user-form button[type="submit"]').click();
    const pending = await page.evaluate(() => offlineApp.pending());
    assert.equal(pending.length, 2);
    assert.ok(!JSON.stringify(pending).includes('NeverPersist123!'));
    await page.reload();
    await page.waitForFunction(() => document.getElementById('tablaMascotas').textContent.includes('Sol offline'));
    assert.equal((await page.evaluate(() => offlineApp.pending())).length, 2);
    disconnected = false; await context.setOffline(false);
    await page.evaluate(() => offlineApp.sync());
    const remaining = await page.evaluate(() => offlineApp.pending());
    assert.equal(remaining.length, 0);
    await page.goto(base + '/auth/login.html');
    disconnected = true; await context.setOffline(true);
    await page.goto(base + '/');
    assert.ok(await page.getByRole('heading', { name: /Pequeñas huellas/ }).isVisible());
    assert.deepEqual(errors, []);
});
